# Generated by Django 5.0.2 on 2024-03-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libros',
            name='imagenLibros',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
    ]
