# Generated by Django 5.0.2 on 2024-03-09 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_app', '0005_libros_imagenlibros'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libros',
            name='imagenLibros',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
